<?php
// $Id$

/**
 * installs role and permissions
 */
function media_image_agents_install() {
  // set default values
  variable_set('media_image_agents_include_subfolders', 0);
  variable_set('media_image_agents_match_all_tags', 0);
  variable_set('media_image_agents_field_folder', array("0" => "0"));
  variable_set('media_image_agents_media_types', implode(",", array_keys(media_type_get_types())));
  variable_set('media_image_agents_field_tags', array());
  variable_set('media_image_agents_affected_roles', array());
  // update the authenticated/anonymous user role
  $role = user_role_load_by_name('authenticated user');
  if(isset($role->rid))
    user_role_revoke_permissions($role->rid, array('view media'));
  $role = user_role_load_by_name('anonymous user');
  if(isset($role->rid))
    user_role_revoke_permissions($role->rid, array('view media'));
}

/**
 * Add config menu
 */
function media_image_agents_menu() {
  $items['admin/config/media/media_image_agents_settings'] = array(
    'title' => 'Media Image Agents Settings',
    'description' => 'Change the settings for media image agents',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_image_agents_settings'),
    'file' => 'media_image_agents.module',
    'access callback' => 'user_access',
    'access arguments' => array('administer media')
  );
  return $items;
}

/**
 * remove role
 */
function media_image_agents_uninstall() {
  variable_del('media_image_agents_include_subfolders');
  variable_del('media_image_agents_match_all_tags');
  variable_del('media_image_agents_field_folder');
  variable_del('media_image_agents_media_types');
  variable_del('media_image_agents_field_tags');
  $old_roles = variable_get('media_image_agents_affected_roles');
  // revoke permissions
  if(count($old_roles)) {
    foreach($old_roles as $rid) {
      _media_image_agents_affect_role($rid, true);
    }
  }
  variable_del('media_image_agents_affected_roles');
}